services:
  api:
    build: .
    ports: ["8000:8000"]
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:16
    env_file:
      - .env
    ports: ["5432:5432"]
