name: Bump & Release

on:
  push:
    branches: [master]

env:
  GIT_USER_EMAIL: gonzasestopal@gmail.com
  GIT_USER_NAME: gonzasestopal

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  bump:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.cz.outputs.version }}
      tag: ${{ steps.cz.outputs.tag }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch tags
        run: git fetch --tags --force

      - id: cz
        name: Commitizen bump & changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_email: ${{ env.GIT_USER_EMAIL }}
          git_name: ${{ env.GIT_USER_NAME }}
          no_raise: 21

      # (Optional) Show what was produced
      - name: Echo bump outputs
        run: |
          echo "version=${{ steps.cz.outputs.version }}"
          echo "tag=${{ steps.cz.outputs.tag }}"

  release:
    # If the bump job is skipped (because the commit is already a bump),
    # this job will also be skipped — desired behavior.
    needs: bump
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch tags
        run: git fetch --tags --force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.bump.outputs.tag }}                # e.g. v0.1.0
          name: Release v${{ needs.bump.outputs.version }}       # e.g. v0.1.0
          body: |
            🚀 Version ${{ needs.bump.outputs.version }} released
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
